### ISSUE TITLE
Unable to set charging value or charge limit

### ISSUE THREAD

**Issue by mignonloic** [Teslemetry/hass-teslemetry#137]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When I try to change the value (number value) of the charge current or charge limit, I've the following error : 
"Échec de l'exécution de l'action number/set_value. Teslemetry command failed, An error occurred while processing the request."

### Reproduction steps

Vehicule is correctly configured on Tesla app (all access granted) and Telsemetry (access type : driver).
I'm able to receive info from the vehicule.
Configuration off hass-teslemetry is standard

### Debug logs

```text
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:27:42 (19 occurrences)
Last logged: 10:30:49

[544424348400] Unexpected exception
[547121553056] Unexpected exception
[547121557088] Unexpected exception
[546658076128] Unexpected exception
[546259656352] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/teslemetry/helpers.py", line 48, in handle_command
    result = await command
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tesla_fleet_api/vehiclespecific.py", line 230, in set_charging_amps
    return await self._parent.set_charging_amps(self.vin, charging_amps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tesla_fleet_api/vehicle.py", line 382, in set_charging_amps
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tesla_fleet_api/teslemetry.py", line 104, in _request
    return await super()._request(method, path, params, json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tesla_fleet_api/teslafleetapi.py", line 133, in _request
    await raise_for_status(resp)
  File "/usr/local/lib/python3.12/site-packages/tesla_fleet_api/exceptions.py", line 377, in raise_for_status
    raise InternalServerError(data)
tesla_fleet_api.exceptions.InternalServerError: An error occurred while processing the request.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 120, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/teslemetry/number.py", line 203, in async_set_native_value
    await self.handle_command(self.entity_description.func(self.api, value))
  File "/config/custom_components/teslemetry/entity.py", line 228, in handle_command
    return await handle_vehicle_command(command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/teslemetry/helpers.py", line 57, in handle_vehicle_command
    result = await handle_command(command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/teslemetry/helpers.py", line 50, in handle_command
    raise HomeAssistantError(f"Teslemetry command failed, {e.message}") from e
homeassistant.exceptions.HomeAssistantError: Teslemetry command failed, An error occurred while processing the request.
```

**Comment by Bre77** [comment]
Sorry I missed this issue, but yes the virtual key is the most likely reason.

https://teslemetry.com/docs/topics/virtualkey

**Comment by mignonloic** [comment]
Virtual key wa effectively the problem. I used Duck duck go browser on my phone and it solved the problem (wasn't working with chrome).
Many Thank's for your help !
