### ISSUE TITLE
Boombox does not work

### ISSUE THREAD

**Issue by zzarne** [Teslemetry/hass-teslemetry#31]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

This may be an issue in the fleet api library. When clicking on the fart button, an exception is reported and no sound is played. Variable 'result' is of type text and empty.
The exception in error handling is like in #30.
EU 2023 Model 3.

### Reproduction steps

1. click fart button

### Debug logs

```text
2024-02-13 14:01:15.438 DEBUG (MainThread) [tesla_fleet_api] Sending request to api/1/vehicles/VVVVVVVVVVVVVVVVV/command/remote_boombox
2024-02-13 14:01:15.439 DEBUG (MainThread) [tesla_fleet_api] Body: {"sound": 0}
2024-02-13 14:01:15.635 DEBUG (MainThread) [tesla_fleet_api] Response Status: 200
2024-02-13 14:01:15.635 DEBUG (MainThread) [tesla_fleet_api] Response Text: 
2024-02-13 14:01:15.635 DEBUG (MainThread) [custom_components.teslemetry] Command result: 
2024-02-13 14:01:15.636 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [CCCCCCCCCCCCCCC] string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/home/hass/.local/lib/python3.12/site-packages/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/.local/lib/python3.12/site-packages/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/home/hass/.local/lib/python3.12/site-packages/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/.local/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hass/.local/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/home/hass/.local/lib/python3.12/site-packages/homeassistant/components/button/__init__.py", line 139, in _async_press_action
    await self.async_press()
  File "/home/hass/.homeassistant/custom_components/teslemetry/button.py", line 84, in async_press
    await self.handle_command(self.entity_description.func(self))
  File "/home/hass/.homeassistant/custom_components/teslemetry/entity.py", line 138, in handle_command
    if not result["response"]["result"]:
           ~~~~~~^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by Bre77** [comment]
Hey @zzarne could you validate if this is still happening? I do believe I made server side changes to address this.

**Comment by zzarne** [comment]
Confirmed to work now.
