### ISSUE TITLE
wall_connectors: TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hass-teslemetry#36]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Looks like an intermittent issue with the wall_connectors endpoint as I have 14 of these in my error logs:

```
This error originated from a custom integration.

Logger: custom_components.teslemetry
Source: helpers/update_coordinator.py:313
Integration: Teslemetry
First occurred: 12:08:26 PM (14 occurrences)
Last logged: 7:19:09 PM

Unexpected error fetching Teslemetry Energy Site Live data: string indices must be integers, not 'str'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/teslemetry/coordinator.py", line 95, in _async_update_data
    wc["din"]: wc for wc in data["response"].get("wall_connectors", [])
                            ~~~~^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
site_info snippet


      "wall_connectors": [
        {
          "device_id": "a4936580-75de-4833-a032-52f882188749",
          "din": "1529455-02-E--PGT22325087207",
          "is_active": true
        },
        {
          "device_id": "216ab0d7-84d6-4aac-baa8-9ada56095440",
          "din": "1529455-02-E--PGT22325086977",
          "is_active": true
        }
      ],
      "disallow_charge_from_grid_with_solar_installed": true,


live_status snippet
```json
    "island_status": "on_grid",
    "storm_mode_active": false,
    "timestamp": "2024-02-18T20:16:49+10:00",
    "wall_connectors": [
      {
        "din": "1529455-02-E--PGT22325087207",
        "vin": "LRWYHCFS9PC851970",
        "wall_connector_state": 5,
        "wall_connector_fault_state": 2,
        "wall_connector_power": 0
      },
      {
        "din": "1529455-02-E--PGT22325086977",
        "vin": "5YJ3F7EC5LF698201",
        "wall_connector_state": 5,
        "wall_connector_fault_state": 2,
        "wall_connector_power": 0
      }
    ]
  }
```
```

**Comment by purcell-lab** [comment]
This issue is resolved.
