### ISSUE TITLE
1.7.4: ignored_variance check for ACChargingEnergyIn is failing.

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hass-teslemetry#44]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

A different TypeError with the stream implementation

Looks like the ignored_variance check for ACChargingEnergyIn is failing.

### Debug logs

```text
2024-03-15 20:02:13.992 DEBUG (MainThread) [teslemetry_stream] event {"data": {"ACChargingEnergyIn": "2.242"}, "createdAt": "2024-03-15T10:02:13.974323725Z", "vin": "5YJ3F7EC5LF698201", "timestamp": 1710496933974}
2024-03-15 20:02:13.992 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/teslemetry_stream/__init__.py", line 193, in listen
    listener(event)
  File "/config/custom_components/teslemetry/entity.py", line 179, in _handle_stream_update
    self._async_value_from_stream(value)
  File "/config/custom_components/teslemetry/sensor.py", line 1124, in _async_value_from_stream
    self._attr_native_value = self.entity_description.value_fn(value)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/variance.py", line 44, in wrapper
    if last_value is not None and abs(value - last_value) < ignored_variance:
                                      ~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'str' and 'float'

**Comment by Bre77** [comment]
I have a fix for this in the next release.

**Comment by Bre77** [comment]
This should have been fixed and has not been completely replaced.
